name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest
      
    - name: Lint with flake8
      run: |
        flake8 app tests
      continue-on-error: true  # Permite que falhas no linting não bloqueiem a CI

    - name: Format with black
      run: |
        black --check app tests
      continue-on-error: true  # Permite que falhas no formatador não bloqueiem a CI

    - name: Test with pytest
      run: |
        pytest
      continue-on-error: true  # Permite que falhas nos testes não bloqueiem a CI
