
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-python-app .

    - name: Run Tests inside Docker
      run: docker run my-python-app
    
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest
      
    - name: Lint with flake8
      run: |
        flake8 src tests
      continue-on-error: true

    - name: Format with black
      run: |
        black --check src tests
      continue-on-error: true
